#!/usr/bin/env bash
set -ex

docker_versions=($(cat docker-versions))
docker_compose_version=($(cat docker-compose-version))

for docker_version in "${docker_versions[@]}"
do
  echo "building image for docker version ${docker_version}"
  docker build \
    --build-arg DIND_IMAGE="docker:${docker_version}-dind" \
    --build-arg DOCKER_ENGINE_VERSION="${docker_version}" \
    --build-arg DOCKER_COMPOSE_VERSION="${docker_compose_version}" \
    --tag "${DOCKER_REPO}:${docker_version}" \
    .
done
