#!/usr/bin/env bash
set -ex

docker_engine_versions=($(cat docker-engine-versions))

for docker_engine_version in "${docker_engine_versions[@]}"
do
  echo "pushing image for docker version ${docker_engine_version}"
  docker push "${DOCKER_REPO}:${docker_engine_version}"
done
